const zodiac = [{
    "animal": "Rat",
    "number": 4,
    "emoji": "🐀",
    "src": "./img/rat.webp",
    "trine": "1st",
    "direction": "North",
    "unicode_symbol": "子",
    "yin_yang": "Yang",
    "season": "Mid-Winter",
    "element": "Water",
    "years": "1900, 1912, 1924, 1936, 1948, 1960, 1972, 1984, 1996, 2008, 2020, 2032",
    "lucky_colors": "gold, blue, green",
    "lucky_numbers": "2, 3, 6, 8",
    "personality_traits": "quick-witted, smart, charming, and persuasive",
    "best_match": "Rat, Dragon, Monkey",
    "average_match": "Snake, Rooster, Ox, Pig, Rabbit, Goat, Dog, Tiger",
    "no_match": "Horse"
  },
  {
    "animal": "Ox",
    "number": 5,
    "emoji": "🐂",
    "src": "./img/ox.webp",
    "trine": "2nd",
    "direction": "North",
    "unicode_symbol": "丑",
    "yin_yang": "Yin",
    "season": "Late Winter",
    "element": "Earth",
    "years": "1901, 1913, 1925, 1937, 1949, 1961, 1973, 1985, 1997, 2009, 2021, 2033",
    "lucky_colors": "blue, red, purple ",
    "lucky_numbers": "8, 9, 3",
    "personality_traits": "patient, kind, stubborn, and conservative",
    "best_match": "Ox, Snake, Rooster",
    "average_match": "Dragon, Monkey, Rat, Dog, Tiger, Horse, Pig, Rabbit",
    "no_match": "Goat"
  },
  {
    "animal": "Tiger",
    "number": 6,
    "emoji": "🐅",
    "src": "./img/tiger.webp",
    "trine": "3rd",
    "direction": "East",
    "unicode_symbol": "寅",
    "yin_yang": "Yang",
    "season": "Early Spring",
    "element": "Wood",
    "years": "1902, 1914, 1926, 1938, 1950, 1962, 1974, 1986, 1998, 2010, 2022, 2034",
    "lucky_colors": "grey, white, blue, purple, orange",
    "lucky_numbers": "1, 4, 7, 8",
    "personality_traits": "authoritative, emotional, courageous, and intense",
    "best_match": "Tiger, Dog, Horse",
    "average_match": "Pig, Rabbit, Goat, Snake, Rooster, Ox, Dragon, Rat",
    "no_match": "Monkey"
  },
  {
    "animal": "Rabbit",
    "number": 7,
    "emoji": "🐇",
    "src": "./img/rabbit.webp",
    "trine": "4th",
    "direction": "East",
    "unicode_symbol": "卯",
    "yin_yang": "Yin",
    "season": "Mid-Spring",
    "element": "Wood",
    "years": "1903, 1915, 1927, 1939, 1951, 1963, 1975, 1987, 1999, 2011, 2023, 2035",
    "lucky_colors": "black, pink, purple, blue, red",
    "lucky_numbers": "3, 6, 9",
    "personality_traits": "popular, compassionate, and sincere",
    "best_match": "Rabbit, Pig, Goat",
    "average_match": "Dog, Tiger, Horse, Dragon, Monkey, Rat, Snake, Ox",
    "no_match": "Rooster"
  },
  {
    "animal": "Dragon",
    "number": 8,
    "emoji": "🐉",
    "src": "./img/dragon.webp",
    "trine": "1st",
    "direction": "East",
    "unicode_symbol": "辰",
    "yin_yang": "Yang",
    "season": "Late Spring",
    "element": "Earth",
    "years": "1904, 1916, 1928, 1940, 1952, 1964, 1976, 1988, 2000, 2012, 2024, 2036",
    "lucky_colors": "gold, silver, yellow",
    "lucky_numbers": "1, 6, 7",
    "personality_traits": "energetic, fearless, warm-hearted, and charismatic",
    "best_match": "Dragon, Monkey, Rat",
    "average_match": "Snake, Rooster, Ox, Pig, Rabbit, Goat, Tiger, Horse",
    "no_match": "Dog"
  },
  {
    "animal": "Snake",
    "number": 9,
    "emoji": "🐍",
    "src": "./img/snake.webp",
    "trine": "2nd",
    "direction": "South",
    "unicode_symbol": "巳",
    "yin_yang": "Yin",
    "season": "Early Summer",
    "element": "Fire",
    "years": "1905, 1917, 1929, 1941, 1953, 1965, 1977, 1989, 2001, 2013, 2025, 2037",
    "lucky_colors": "red, yellow, black",
    "lucky_numbers": "2, 8",
    "personality_traits": "charming, gregarious, introverted, generous, and smart",
    "best_match": "Snake, Rooster, Ox",
    "average_match": "Dragon, Monkey, Rat, Dog, Tiger, Horse, Rabbit, Goat",
    "no_match": "Pig"
  },
  {
    "animal": "Horse",
    "number": 10,
    "emoji": "🐎",
    "src": "./img/horse.webp",
    "trine": "3rd",
    "direction": "South",
    "unicode_symbol": "午",
    "yin_yang": "Yang",
    "season": "Mid-Summer",
    "element": "Fire",
    "years": "1906, 1918, 1930, 1942, 1954, 1966, 1978, 1990, 2002, 2014, 2026, 2038",
    "lucky_colors": "gold, yellow, red, blue",
    "lucky_numbers": "1, 4, 5, 7, 9",
    "personality_traits": "energetic, independent, impatient, and enjoy traveling",
    "best_match": "Horse, Dog, Tiger",
    "average_match": "Pig, Rabbit, Goat, Snake, Rooster, Ox, Dragon, Monkey",
    "no_match": "Rat"
  },
  {
    "animal": "Goat",
    "number": 11,
    "emoji": "🐐",
    "src": "./img/goat.webp",
    "trine": "4th",
    "direction": "South",
    "unicode_symbol": "未",
    "yin_yang": "Yin",
    "season": "Late Summer",
    "element": "Earth",
    "years": "1907, 1919, 1931, 1943, 1955, 1967, 1979, 1991, 2003, 2015, 2027, 2039",
    "lucky_colors": "green, red, purple",
    "lucky_numbers": "2, 3, 4, 7, 9",
    "personality_traits": "mild-mannered, shy, kind, and peace-loving",
    "best_match": "Goat, Pig, Rabbit",
    "average_match": "Dog, Tiger, Horse, Dragon, Monkey, Rat, Snake, Rooster",
    "no_match": "Ox"
  },
  {
    "animal": "Monkey",
    "number": 0,
    "emoji": "🐒",
    "src": "./img/monkey.webp",
    "trine": "1st",
    "direction": "West",
    "unicode_symbol": "申",
    "yin_yang": "Yang",
    "season": "Early Autumn",
    "element": "Metal",
    "years": "1908, 1920, 1932, 1944, 1956, 1968, 1980, 1992, 2004, 2016, 2028, 2040",
    "lucky_colors": "white, gold, blue",
    "lucky_numbers": "3, 4, 7, 9",
    "personality_traits": "fun, energetic, and active",
    "best_match": "Monkey, Dragon, Rat",
    "average_match": "Snake, Rooster, Ox, Pig, Rabbit, Goat, Dog, Horse",
    "no_match": "Tiger"
  },
  {
    "animal": "Rooster",
    "number": 1,
    "emoji": "🐓",
    "src": "./img/rooster.webp",
    "trine": "2nd",
    "direction": "West",
    "unicode_symbol": "酉",
    "yin_yang": "Yin",
    "season": "Mid-Autumn",
    "element": "Metal",
    "years": "1909, 1921, 1933, 1945, 1957, 1969, 1981, 1993, 2005, 2017, 2029, 2041",
    "lucky_colors": "gold, brown, yellow",
    "lucky_numbers": "5, 7, 8",
    "personality_traits": "independent, practical, hard-working, and observant",
    "best_match": "Rooster, Snake, Ox",
    "average_match": "Dragon, Monkey, Rat, Dog, Tiger, Horse, Pig, Goat",
    "no_match": "Rabbit"
  },
  {
    "animal": "Dog",
    "number": 2,
    "emoji": "🐕",
    "src": "./img/dog.webp",
    "trine": "3rd",
    "direction": "West",
    "unicode_symbol": "戌",
    "yin_yang": "Yang",
    "season": "Late Autumn",
    "element": "Earth",
    "years": "1910, 1922, 1934, 1946, 1958, 1970, 1982, 1994, 2006, 2018, 2030, 2042",
    "lucky_colors": "green, red, purple",
    "lucky_numbers": "3, 4, 9",
    "personality_traits": "patient, diligent, generous, faithful, and kind",
    "best_match": "Dog, Tiger, Horse",
    "average_match": "Pig, Rabbit, Goat, Snake, Rooster, Ox, Monkey, Rat",
    "no_match": "Dragon"
  },
  {
    "animal": "Pig",
    "number": 3,
    "emoji": "🐖",
    "src": "./img/pig.webp",
    "trine": "4th",
    "direction": "North",
    "unicode_symbol": "亥",
    "yin_yang": "Yin",
    "season": "Early Winter",
    "element": "Water",
    "years": "1911, 1923, 1935, 1947, 1959, 1971, 1983, 1995, 2007, 2019, 2031, 2043",
    "lucky_colors": "yellow",
    "lucky_numbers": "2, 5, 6, 8",
    "personality_traits": "loving, tolerant, honest, and appreciative of luxury",
    "best_match": "Pig, Rabbit, Goat",
    "average_match": "Dog, Tiger, Horse, Dragon, Monkey, Rat, Rooster, Ox",
    "no_match": "Snake"
  }
]

module.exports = zodiac
